server:
  port: 8081
  servlet:
    context-path: /Ecommerce
spring:
  datasource:
    password: amthambenem169
    url: jdbc:mysql://localhost:3306/ecommercedb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 433167358084-5jlafef6c23lqoqavgtacfpe51ev3tjd.apps.googleusercontent.com
            client-secret: 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
            scope: 
             - email
             - profile
          facebook:
            client-id: 308991841956808
            client-secret: 477b5c9cd568300fdd94457be415fb1f
            scope: 
            - email
            - public_profile
          